version: '3.4'

services:
  cicloiv:
    image: cicloiv
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8021:8021
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
